config/routes.rb
Rails.application.routes.draw do





  root  'docpages#home'

  get'about' => 'docpages#about'

  get 'support' => 'docpages#support'
  get 'mail' => 'docpages#mail'
  get 'join' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  resources :users
  resources :logins
  resources :documents
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  def create 
    user = User.find_by(name: params[:login][:name])
    if user && user.authenticate(params[:login][:password])
       if user.activated? 
        log_in user 
        params[:login][:remember_me]== '1' ? remember(user) : forget(user)
        flash[:yeah]= "Welcome back"
        redirect_back_or user
       else
         flash[:nasty] = "Account not activated"
         redirect_to root_url
       end
    else
      flash[:nasty] = "Invalid Creditials Name and username does not match!!"
      render 'new'
    end
  end


  def destroy
    logout if logged_in?
    redirect_to root_url
  end
end

app/helpers/logins_helper.rb
module LoginsHelper

  #login a given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
    @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end

  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
redirect_to(session[:forwarding_url] || default)
session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?

  end
end

app/views/logins/new.html.erb
<div class="row">
    <% provide(:title, "Login") %>
<h1>Login Here</h1>
<%= form_for(:login, url: login_path)  do |f| %>
    <div class="small-4">
    <%= f.label :name, placeholder: "name" %>
    <%= f.text_field :name %>    </div>
    <div class="small-4">
    <%= f.label :password, placeholder: "password" %>
    <%= f.password_field :password %>
    <%=  link_to "(forgot password)", new_password_reset_path %>
    </div>
    <div class="small-4">
    <%= f.label :remember do  %>
        <%= f.check_box :Remember %> 
        <span> Remember me here </span>
    <% end %>
    </div>

    <%= f.submit "Login"%> 

    <p> You new here???  <%= link_to "Join now!", join_path %></p>
<% end %>
</div>