config/routes.rb
Rails.application.routes.draw do





  root  'docpages#home'

  get'about' => 'docpages#about'

  get 'support' => 'docpages#support'
  get 'mail' => 'docpages#mail'
  get 'join' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  resources :users
  resources :logins
  resources :documents
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/docpages_controller.rb
class DocpagesController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "About", :about_path
  add_breadcrumb "Support", :support_path

  def home
  end

  def about
  end

  def support
  end
end

app/helpers/docpages_helper.rb
module DocpagesHelper
end

app/views/docpages/about.html.erb
<div class="row">
    <% provide(:title, "About") %>
<h1> About Document Vault </h1>
<%= image_tag("docu1.jpg") %>
<p>We keep track of all the documents you want and have and need
Awesome stuff you can do here
<ul>
    <li> Search for documents</li>
    <li> Upload documents</li>
    <li> View all your  friends documents </li>
    <li> See comments on your documents</li>
</p>
<p>
We started this application to enable user to be able to 
share documents that can help one in his/her area of research or study.
Also it helps keep the information going and be passed around to the appropriate people
Our clients are happy of our services so far and we get emails daily commending 
us of our infinite help 
All services are free here unless  you want to use the vault for a companies 
documents or store a ridiculously large number of files

</p>
</body>
</div>

app/views/docpages/home.html.erb
<% provide(:title, "Home") %>
<h1> Document Vault</h1>
<div class="row">
    <%= image_tag("file2.jpg") %>
</div>
<div class="row">
    <h3 align="center"> Whatsapp with us?</h3>
    <div class="medium-4 columns">
        <p><%= fa_icon "camera-retro" %></p>

        <p>We keep track of all the documents you want and have and need <br>
        Awesome stuff you can do here
        <ul>
            <li> Search for documents</li>
            <li> Upload documents</li>
            <li> View all your  friends documents </li>
            <li> See comments on your documents</li>
        </p>
        <p>
    </div>
    <div class="medium-4 columns">
        <p> Hurry Join to start enjoying our awesome services!!!!
        This is awesome for an organisation, individuals or even friends and 
        classmates who would like to share documents, assignments amongst themselves.
        This web application can also be used by upcoming writers for their articles and 
        thereby know if they have a shot in this world of writing.
        Lazy and wierd folks can also  write a stories for people to read without
        the idea of making money out from it.</p>
        <% unless logged_in? %>
            <%= link_to "Join Now !!!", join_path %> 
        <% end %>
    </div>
    <div class="medium-4 columns">
        <p> This web applicaton was inspired by the need of different organisation to share documents
        between departments for report writing and performance analysis.
        Having to look for the secretary of a particular department to get the information about a particular project is hectic
        How awesome can it be if we just had a place you can search through to look for a particular document when need!!
        </p>
    </div>
</div>

app/views/docpages/mail.html.erb
<%= form_tag do  %>
    <%= label_tag :Content %>
    <%= text_area_tag :content
         %><br><br>
        <%= label_tag :Name %>
        <%= text_field_tag :name  %><br><br>
        <%= submit_tag "Mail us" %>
    <% end %>

app/views/docpages/support.html.erb
    <% provide(:title, "Support") %>
<h1> Support </h1>
<%= image_tag("doc.jpg", width: "400", height: "200", alt: "logo") %>
<body>
<p>
Mail to us of particularly anything even if
you want to  criticize me, point a bug, concern or u just wonna say hi<br>
Just #put it out there
</p>
<p>
Feel free to raise a concern here and even for any clarifications<br>
Just mail me Bunch!!!
</p>
<p> I promise no judging
</p>
<%= link_to "Mail us",mail_path %>
</body>