config/routes.rb
Rails.application.routes.draw do





  root  'docpages#home'

  get'about' => 'docpages#about'

  get 'support' => 'docpages#support'
  get 'mail' => 'docpages#mail'
  get 'join' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  resources :users
  resources :logins
  resources :documents
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :documents
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  NAME = /[a-zA-Z]*/
  REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 },
  format: { with: /\A[a-zA-Z]+\z/, }
  validates :email, presence: true, uniqueness: true,
    format: { with: REGEX }, length: { maximum: 30 } 
  validates :password, length: { minimum: 5  }
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated , true)
    update_attribute(:activated_at, Time.zone.now)
  end
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  def send_password_reset_digest
    UserMailer.password_reset(self).deliver_now
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at,   Time.zone.now)
  end


  def password_reset_expired?
      reset_sent_at < 2.hours.ago
  end


  private
  def downcase_email
    self.email = email.downcase
  end
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest= User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update,  :show ]
  before_action :correct_user, only: [:edit, :update]
  def new
  @user = User.new
  end

  def create
    @user = User.new(join_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:yeah] = "Welcome to the application, Check email to activate account "
      redirect_to root_url
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
    @documents = @user.documents
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(join_params)
      flash[:yeah] = "Profile has been updated!!"
      redirect_to @user
    else 
      render 'edit'
    end
  end

  private
  def join_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation )
  end

 
  def correct_user
    @user = User.find(params[:id])
    redirect_to (root_url) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
    <% provide(:title, "Edit") %>
<h1> Edit Information </h1>
<%= form_for(@user) do  |f|%>
    <%= render 'shared/errors', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name,  placeholder: "Name" %><br><br>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email" %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" %><br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm"  %><br><br>
    <%= f.submit "Save Changes" %>
    <% end %>

app/views/users/index.html.erb
    <% provide(:title, "Users") %>
<h1>All the Users </h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
<% @users.each do |user| %>
        <tr>
        <td> <%= user.id %></td>
        <td> <%=  user.name  %>  </td>
        <td><%= user.email %></td>
        </tr>
<% end %>
    </table>

app/views/users/new.html.erb
<div class="row">
    <% provide(:title, "Join here") %>
<h1>Join Document Vault!!</h1>
<%= form_for(@user) do  |f|%>
    <%= render 'shared/errors', object: f.object %>
    <div class="small-5">
    <%= f.label :name %>
    <%= f.text_field :name,  placeholder: "Name" %>
    </div>
    <div class="small-5">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email" %>
    </div>
    <div class="small-5">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" %>
    </div>
    <div class="small-5">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm"  %>
    </div>
    <%= f.submit "Join" %>
    </div>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<h1>Hello <%= @user.name %>!!!!! </h1>
<strong>You have  uploaded <%= @documents.count %> documents</strong>
<table>
    <tr>
        <th> Title</th>
        <th>Link</th>
        <th>Department</th>
        <th>View Doc</th>
        <th></th>
    </tr>
    <% @documents.each do |document| %>
        <tr>
            <td><%= document.title %></td>
            <td><%= link_to (document.link), document_path(id: document.id) %></td>
            <td><%= document.department %></td>
            <td> <%= link_to"Download Document", document.attachment_url %></td>
            <td><%= link_to "Edit",edit_document_path(document)  %></td> 
            <td><%= link_to "Delete",(document), method: :delete, data: { confirm: "You sure about this?" } %>
    </tr>
<% end %>
</table>
<p align="center"><%= link_to "Edit user", edit_user_path(current_user), class:"button" %> 
      <%= link_to "New doc", new_document_path, class: "button" %> </p>