config/routes.rb
Rails.application.routes.draw do





  root  'docpages#home'

  get'about' => 'docpages#about'

  get 'support' => 'docpages#support'
  get 'mail' => 'docpages#mail'
  get 'join' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  resources :users
  resources :logins
  resources :documents
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
            This form contains
            <%= pluralize(object.errors.count, "error") %>
    <div id = "error">
        <% object.errors.full_messages.each do |message| %>
            <ul>
                <li>  <%= message %> </li>
            </ul>
        <% end %>
    </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="top-bar">
    <div class="top-bar-left">
        <ul>
            <li><%= link_to "Home", root_url %></li>
            <li> <%= link_to "About", about_path %></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <% if logged_in? %>
            <ul>
                <li> <%= link_to "Users", users_path %> </li>
                <li><%= link_to "Documents", documents_path %> </li>
                <li><%= link_to "Profile", current_user %> </li>
                <li><%= link_to "Logout", logout_path, method: :delete %> </li>
                </ul>
            <% else %>
                <li><%= link_to "Login", login_path %></li>&nbsp; &nbsp; &nbsp; &nbsp; 
                <li><%= link_to "Sign up", join_path %></li>
            <% end %>

            </ul>
    </div>
</nav>